// src/components/admin/dashboard-charts.tsx
"use client";

import * as React from "react";
import { Card, CardContent } from "@/components/ui/card";
import {
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
  ChartLegend,
} from "@/components/ui/chart";

import {
  Area,
  AreaChart,
  Bar,
  BarChart,
  Pie,
  PieChart,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  ResponsiveContainer,
} from "recharts";

type Point = { label: string; value: number };

function ChartCard(props: {
  title: string;
  config: any; // keep flexible; shadcn ChartConfig type is optional
  children: React.ReactNode;
}) {
  const { title, config, children } = props;

  return (
    <Card className="border-border bg-card text-card-foreground">
      <CardContent className="p-5">
        <div className="flex items-center justify-between">
          <p className="text-sm font-semibold text-foreground">{title}</p>
        </div>

        <div className="mt-3 h-56 w-full">
          <ChartContainer config={config} className="h-full w-full">
            {children as any}
          </ChartContainer>
        </div>
      </CardContent>
    </Card>
  );
}

export function DashboardCharts(props: {
  usersDaily: Point[];
  setsDaily: Point[];
  favoritesDaily: Point[];
  festivalStatus: { name: string; value: number }[];
}) {
  const { usersDaily, setsDaily, festivalStatus } = props;

  return (
    <div className="grid gap-4 lg:grid-cols-3">
      {/* USERS */}
      <ChartCard
        title="New users"
        // ChartContainer will create: --color-value from this
        config={{ value: { label: "Users", color: "var(--chart-1)" } }}
      >
        <ResponsiveContainer width="100%" height="100%">
          <AreaChart data={usersDaily} margin={{ left: 8, right: 8, top: 8, bottom: 0 }}>
            <CartesianGrid vertical={false} stroke="var(--border)" />
            <XAxis
              dataKey="label"
              tickLine={false}
              axisLine={false}
              tick={{ fill: "var(--muted-foreground)" }}
            />
            <YAxis
              tickLine={false}
              axisLine={false}
              width={28}
              tick={{ fill: "var(--muted-foreground)" }}
            />
            <ChartTooltip content={<ChartTooltipContent />} />

            {/* Use the CSS var generated by ChartContainer */}
            <Area
              dataKey="value"
              type="monotone"
              stroke="var(--color-value)"
              fill="var(--color-value)"
              fillOpacity={0.22}
              dot={false}
              activeDot={{ r: 4 }}
            />
          </AreaChart>
        </ResponsiveContainer>
      </ChartCard>

      {/* SETS */}
      <ChartCard
        title="Sets created"
        config={{ value: { label: "Sets", color: "var(--chart-2)" } }}
      >
        <ResponsiveContainer width="100%" height="100%">
          <BarChart data={setsDaily} margin={{ left: 8, right: 8, top: 8, bottom: 0 }}>
            <CartesianGrid vertical={false} stroke="var(--border)" />
            <XAxis
              dataKey="label"
              tickLine={false}
              axisLine={false}
              tick={{ fill: "var(--muted-foreground)" }}
            />
            <YAxis
              tickLine={false}
              axisLine={false}
              width={28}
              tick={{ fill: "var(--muted-foreground)" }}
            />
            <ChartTooltip content={<ChartTooltipContent />} />

            <Bar dataKey="value" radius={4} fill="var(--color-value)" stroke="var(--color-value)" />
          </BarChart>
        </ResponsiveContainer>
      </ChartCard>

      {/* FESTIVALS PIE */}
      <ChartCard
        title="Festival status"
        // Keys should match festivalStatus[].name exactly
        config={{
          Published: { label: "Published", color: "var(--chart-1)" },
          Drafts: { label: "Drafts", color: "var(--chart-2)" },
        }}
      >
        <ResponsiveContainer width="100%" height="100%">
          <PieChart>
            <Pie
              data={festivalStatus}
              dataKey="value"
              nameKey="name"
              innerRadius={45}
              outerRadius={70}
              paddingAngle={4}
              stroke="var(--card)" // subtle separation ring
              strokeWidth={2}
            >
              {festivalStatus.map((entry, i) => (
                <Cell
                  key={`${entry.name}-${i}`}
                  // Use ChartContainer-generated vars: --color-Published, --color-Drafts, etc.
                  fill={`var(--color-${entry.name})`}
                />
              ))}
            </Pie>

            <ChartTooltip content={<ChartTooltipContent />} />
            <ChartLegend />
          </PieChart>
        </ResponsiveContainer>
      </ChartCard>
    </div>
  );
}
